# Generated by Django 3.2.25 on 2024-07-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
